language: php
services:
  - docker
script:
  - | 
    if ["$TRAVIS_BRANCH" = "master" ]; then 
      sed -i -e 's/{WORDPRESS_URL}/https:\/\/link-lives.dk/' Dockerfile 
    fi
  - |
    if ["$TRAVIS_BRANCH" = "development" ]; then 
      sed -i -e 's/{WORDPRESS_URL}/https:\/\/beta.link-lives.dk/' Dockerfile 
    fi
  - docker build .
deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: eu-west-1
    app: LinkLivesCMS
    env: linklives-6
    bucket: elasticbeanstalk-eu-west-1-282251075226
    edge: true
    on:
      branch: master
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: eu-west-1
    app: LinkLivesCMS
    env: link-lives-12
    bucket: elasticbeanstalk-eu-west-1-282251075226
    edge: true
    on:
      branch: development
